// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/browserservice.proto

package browserservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WaitUntil is how far into a navigation to wait, mirroring the browser's enum.
type WaitUntil int32

const (
	WaitUntil_WAIT_UNTIL_UNSPECIFIED         WaitUntil = 0
	WaitUntil_WAIT_UNTIL_COMMIT              WaitUntil = 1
	WaitUntil_WAIT_UNTIL_DOM_CONTENT_LOADED  WaitUntil = 2
	WaitUntil_WAIT_UNTIL_LOAD                WaitUntil = 3
	WaitUntil_WAIT_UNTIL_NETWORK_ALMOST_IDLE WaitUntil = 4
	WaitUntil_WAIT_UNTIL_NETWORK_IDLE        WaitUntil = 5
)

// Enum value maps for WaitUntil.
var (
	WaitUntil_name = map[int32]string{
		0: "WAIT_UNTIL_UNSPECIFIED",
		1: "WAIT_UNTIL_COMMIT",
		2: "WAIT_UNTIL_DOM_CONTENT_LOADED",
		3: "WAIT_UNTIL_LOAD",
		4: "WAIT_UNTIL_NETWORK_ALMOST_IDLE",
		5: "WAIT_UNTIL_NETWORK_IDLE",
	}
	WaitUntil_value = map[string]int32{
		"WAIT_UNTIL_UNSPECIFIED":         0,
		"WAIT_UNTIL_COMMIT":              1,
		"WAIT_UNTIL_DOM_CONTENT_LOADED":  2,
		"WAIT_UNTIL_LOAD":                3,
		"WAIT_UNTIL_NETWORK_ALMOST_IDLE": 4,
		"WAIT_UNTIL_NETWORK_IDLE":        5,
	}
)

func (x WaitUntil) Enum() *WaitUntil {
	p := new(WaitUntil)
	*p = x
	return p
}

func (x WaitUntil) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaitUntil) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_browserservice_proto_enumTypes[0].Descriptor()
}

func (WaitUntil) Type() protoreflect.EnumType {
	return &file_proto_browserservice_proto_enumTypes[0]
}

func (x WaitUntil) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaitUntil.Descriptor instead.
func (WaitUntil) EnumDescriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{0}
}

// Cookie is one cookie as the browser holds it, in the profile's own shape so
// the control plane relays it without reinterpreting anything.
type Cookie struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value  string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Domain string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path   string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// Unix seconds. Absent for a session cookie.
	Expires       *float64 `protobuf:"fixed64,5,opt,name=expires,proto3,oneof" json:"expires,omitempty"`
	Secure        bool     `protobuf:"varint,6,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool     `protobuf:"varint,7,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	SameSite      string   `protobuf:"bytes,8,opt,name=same_site,json=sameSite,proto3" json:"same_site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	mi := &file_proto_browserservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{0}
}

func (x *Cookie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cookie) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cookie) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Cookie) GetExpires() float64 {
	if x != nil && x.Expires != nil {
		return *x.Expires
	}
	return 0
}

func (x *Cookie) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Cookie) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

func (x *Cookie) GetSameSite() string {
	if x != nil {
		return x.SameSite
	}
	return ""
}

type OpenRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Browser          string                 `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserProfileId string                 `protobuf:"bytes,2,opt,name=browser_profile_id,json=browserProfileId,proto3" json:"browser_profile_id,omitempty"`
	AppId            string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ExecutionId      string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// The rustenium-identity record, as JSON, and never empty — this service has
	// no database to read a profile from, so the control plane resolves it: the
	// profile's when one is named, otherwise a coherent machine drawn for this
	// session alone.
	//
	// Opaque because that crate owns the schema, so a field added to an identity
	// is not a release here.
	Identity      []byte `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_proto_browserservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{1}
}

func (x *OpenRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *OpenRequest) GetBrowserProfileId() string {
	if x != nil {
		return x.BrowserProfileId
	}
	return ""
}

func (x *OpenRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *OpenRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *OpenRequest) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_proto_browserservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{2}
}

func (x *OpenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// The commands, shaped after the browser's own functions. They mirror
// browser.proto's because the control plane relays them without reinterpreting
// anything: a difference between the two would be a translation, and a
// translation is a place for the meaning to drift.
type NavigateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Url       string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Absent sends no Referer, which is not the same as sending an empty one.
	Referer       *string `protobuf:"bytes,3,opt,name=referer,proto3,oneof" json:"referer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateRequest) Reset() {
	*x = NavigateRequest{}
	mi := &file_proto_browserservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateRequest) ProtoMessage() {}

func (x *NavigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateRequest.ProtoReflect.Descriptor instead.
func (*NavigateRequest) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{3}
}

func (x *NavigateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NavigateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NavigateRequest) GetReferer() string {
	if x != nil && x.Referer != nil {
		return *x.Referer
	}
	return ""
}

type NavigateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateResponse) Reset() {
	*x = NavigateResponse{}
	mi := &file_proto_browserservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateResponse) ProtoMessage() {}

func (x *NavigateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateResponse.ProtoReflect.Descriptor instead.
func (*NavigateResponse) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{4}
}

type WaitForNavigationRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Unspecified is Load, which is the browser's own default.
	WaitUntil WaitUntil `protobuf:"varint,2,opt,name=wait_until,json=waitUntil,proto3,enum=neurun.browserservice.v1.WaitUntil" json:"wait_until,omitempty"`
	// The browser takes a Duration; this is it in milliseconds, which is as fine
	// as a navigation timeout is ever set. Zero leaves its default in place.
	TimeoutMs     uint32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForNavigationRequest) Reset() {
	*x = WaitForNavigationRequest{}
	mi := &file_proto_browserservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForNavigationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForNavigationRequest) ProtoMessage() {}

func (x *WaitForNavigationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForNavigationRequest.ProtoReflect.Descriptor instead.
func (*WaitForNavigationRequest) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{5}
}

func (x *WaitForNavigationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WaitForNavigationRequest) GetWaitUntil() WaitUntil {
	if x != nil {
		return x.WaitUntil
	}
	return WaitUntil_WAIT_UNTIL_UNSPECIFIED
}

func (x *WaitForNavigationRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WaitForNavigationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForNavigationResponse) Reset() {
	*x = WaitForNavigationResponse{}
	mi := &file_proto_browserservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForNavigationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForNavigationResponse) ProtoMessage() {}

func (x *WaitForNavigationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForNavigationResponse.ProtoReflect.Descriptor instead.
func (*WaitForNavigationResponse) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{6}
}

type GetCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCookiesRequest) Reset() {
	*x = GetCookiesRequest{}
	mi := &file_proto_browserservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookiesRequest) ProtoMessage() {}

func (x *GetCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookiesRequest.ProtoReflect.Descriptor instead.
func (*GetCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetCookiesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetCookiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The whole jar. Empty is ambiguous by nature — a browser holding nothing
	// and a browser that would not say look the same from here.
	Cookies       []*Cookie `protobuf:"bytes,1,rep,name=cookies,proto3" json:"cookies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCookiesResponse) Reset() {
	*x = GetCookiesResponse{}
	mi := &file_proto_browserservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookiesResponse) ProtoMessage() {}

func (x *GetCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookiesResponse.ProtoReflect.Descriptor instead.
func (*GetCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{8}
}

func (x *GetCookiesResponse) GetCookies() []*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type SetCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cookies       []*Cookie              `protobuf:"bytes,2,rep,name=cookies,proto3" json:"cookies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCookiesRequest) Reset() {
	*x = SetCookiesRequest{}
	mi := &file_proto_browserservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCookiesRequest) ProtoMessage() {}

func (x *SetCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCookiesRequest.ProtoReflect.Descriptor instead.
func (*SetCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{9}
}

func (x *SetCookiesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetCookiesRequest) GetCookies() []*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type SetCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCookiesResponse) Reset() {
	*x = SetCookiesResponse{}
	mi := &file_proto_browserservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCookiesResponse) ProtoMessage() {}

func (x *SetCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCookiesResponse.ProtoReflect.Descriptor instead.
func (*SetCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{10}
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_browserservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{11}
}

func (x *CloseRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_browserservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{12}
}

type DisplayChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayChunk) Reset() {
	*x = DisplayChunk{}
	mi := &file_proto_browserservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayChunk) ProtoMessage() {}

func (x *DisplayChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browserservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayChunk.ProtoReflect.Descriptor instead.
func (*DisplayChunk) Descriptor() ([]byte, []int) {
	return file_proto_browserservice_proto_rawDescGZIP(), []int{13}
}

func (x *DisplayChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_browserservice_proto protoreflect.FileDescriptor

const file_proto_browserservice_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/browserservice.proto\x12\x18neurun.browserservice.v1\"\xdb\x01\n" +
	"\x06Cookie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1d\n" +
	"\aexpires\x18\x05 \x01(\x01H\x00R\aexpires\x88\x01\x01\x12\x16\n" +
	"\x06secure\x18\x06 \x01(\bR\x06secure\x12\x1b\n" +
	"\thttp_only\x18\a \x01(\bR\bhttpOnly\x12\x1b\n" +
	"\tsame_site\x18\b \x01(\tR\bsameSiteB\n" +
	"\n" +
	"\b_expires\"\xab\x01\n" +
	"\vOpenRequest\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12,\n" +
	"\x12browser_profile_id\x18\x02 \x01(\tR\x10browserProfileId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12\x1a\n" +
	"\bidentity\x18\x05 \x01(\fR\bidentity\"-\n" +
	"\fOpenResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"m\n" +
	"\x0fNavigateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\areferer\x18\x03 \x01(\tH\x00R\areferer\x88\x01\x01B\n" +
	"\n" +
	"\b_referer\"\x12\n" +
	"\x10NavigateResponse\"\x9c\x01\n" +
	"\x18WaitForNavigationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12B\n" +
	"\n" +
	"wait_until\x18\x02 \x01(\x0e2#.neurun.browserservice.v1.WaitUntilR\twaitUntil\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\"\x1b\n" +
	"\x19WaitForNavigationResponse\"2\n" +
	"\x11GetCookiesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"P\n" +
	"\x12GetCookiesResponse\x12:\n" +
	"\acookies\x18\x01 \x03(\v2 .neurun.browserservice.v1.CookieR\acookies\"n\n" +
	"\x11SetCookiesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12:\n" +
	"\acookies\x18\x02 \x03(\v2 .neurun.browserservice.v1.CookieR\acookies\"\x14\n" +
	"\x12SetCookiesResponse\"-\n" +
	"\fCloseRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x0f\n" +
	"\rCloseResponse\"\"\n" +
	"\fDisplayChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*\xb7\x01\n" +
	"\tWaitUntil\x12\x1a\n" +
	"\x16WAIT_UNTIL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WAIT_UNTIL_COMMIT\x10\x01\x12!\n" +
	"\x1dWAIT_UNTIL_DOM_CONTENT_LOADED\x10\x02\x12\x13\n" +
	"\x0fWAIT_UNTIL_LOAD\x10\x03\x12\"\n" +
	"\x1eWAIT_UNTIL_NETWORK_ALMOST_IDLE\x10\x04\x12\x1b\n" +
	"\x17WAIT_UNTIL_NETWORK_IDLE\x10\x052\xd9\x05\n" +
	"\x0eBrowserService\x12U\n" +
	"\x04Open\x12%.neurun.browserservice.v1.OpenRequest\x1a&.neurun.browserservice.v1.OpenResponse\x12a\n" +
	"\bNavigate\x12).neurun.browserservice.v1.NavigateRequest\x1a*.neurun.browserservice.v1.NavigateResponse\x12|\n" +
	"\x11WaitForNavigation\x122.neurun.browserservice.v1.WaitForNavigationRequest\x1a3.neurun.browserservice.v1.WaitForNavigationResponse\x12g\n" +
	"\n" +
	"GetCookies\x12+.neurun.browserservice.v1.GetCookiesRequest\x1a,.neurun.browserservice.v1.GetCookiesResponse\x12g\n" +
	"\n" +
	"SetCookies\x12+.neurun.browserservice.v1.SetCookiesRequest\x1a,.neurun.browserservice.v1.SetCookiesResponse\x12X\n" +
	"\x05Close\x12&.neurun.browserservice.v1.CloseRequest\x1a'.neurun.browserservice.v1.CloseResponse\x12c\n" +
	"\rStreamDisplay\x12&.neurun.browserservice.v1.DisplayChunk\x1a&.neurun.browserservice.v1.DisplayChunk(\x010\x01BHZFgithub.com/neurun-io/neurun/internal/browserservicepb;browserservicepbb\x06proto3"

var (
	file_proto_browserservice_proto_rawDescOnce sync.Once
	file_proto_browserservice_proto_rawDescData []byte
)

func file_proto_browserservice_proto_rawDescGZIP() []byte {
	file_proto_browserservice_proto_rawDescOnce.Do(func() {
		file_proto_browserservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_browserservice_proto_rawDesc), len(file_proto_browserservice_proto_rawDesc)))
	})
	return file_proto_browserservice_proto_rawDescData
}

var file_proto_browserservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_browserservice_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_browserservice_proto_goTypes = []any{
	(WaitUntil)(0),                    // 0: neurun.browserservice.v1.WaitUntil
	(*Cookie)(nil),                    // 1: neurun.browserservice.v1.Cookie
	(*OpenRequest)(nil),               // 2: neurun.browserservice.v1.OpenRequest
	(*OpenResponse)(nil),              // 3: neurun.browserservice.v1.OpenResponse
	(*NavigateRequest)(nil),           // 4: neurun.browserservice.v1.NavigateRequest
	(*NavigateResponse)(nil),          // 5: neurun.browserservice.v1.NavigateResponse
	(*WaitForNavigationRequest)(nil),  // 6: neurun.browserservice.v1.WaitForNavigationRequest
	(*WaitForNavigationResponse)(nil), // 7: neurun.browserservice.v1.WaitForNavigationResponse
	(*GetCookiesRequest)(nil),         // 8: neurun.browserservice.v1.GetCookiesRequest
	(*GetCookiesResponse)(nil),        // 9: neurun.browserservice.v1.GetCookiesResponse
	(*SetCookiesRequest)(nil),         // 10: neurun.browserservice.v1.SetCookiesRequest
	(*SetCookiesResponse)(nil),        // 11: neurun.browserservice.v1.SetCookiesResponse
	(*CloseRequest)(nil),              // 12: neurun.browserservice.v1.CloseRequest
	(*CloseResponse)(nil),             // 13: neurun.browserservice.v1.CloseResponse
	(*DisplayChunk)(nil),              // 14: neurun.browserservice.v1.DisplayChunk
}
var file_proto_browserservice_proto_depIdxs = []int32{
	0,  // 0: neurun.browserservice.v1.WaitForNavigationRequest.wait_until:type_name -> neurun.browserservice.v1.WaitUntil
	1,  // 1: neurun.browserservice.v1.GetCookiesResponse.cookies:type_name -> neurun.browserservice.v1.Cookie
	1,  // 2: neurun.browserservice.v1.SetCookiesRequest.cookies:type_name -> neurun.browserservice.v1.Cookie
	2,  // 3: neurun.browserservice.v1.BrowserService.Open:input_type -> neurun.browserservice.v1.OpenRequest
	4,  // 4: neurun.browserservice.v1.BrowserService.Navigate:input_type -> neurun.browserservice.v1.NavigateRequest
	6,  // 5: neurun.browserservice.v1.BrowserService.WaitForNavigation:input_type -> neurun.browserservice.v1.WaitForNavigationRequest
	8,  // 6: neurun.browserservice.v1.BrowserService.GetCookies:input_type -> neurun.browserservice.v1.GetCookiesRequest
	10, // 7: neurun.browserservice.v1.BrowserService.SetCookies:input_type -> neurun.browserservice.v1.SetCookiesRequest
	12, // 8: neurun.browserservice.v1.BrowserService.Close:input_type -> neurun.browserservice.v1.CloseRequest
	14, // 9: neurun.browserservice.v1.BrowserService.StreamDisplay:input_type -> neurun.browserservice.v1.DisplayChunk
	3,  // 10: neurun.browserservice.v1.BrowserService.Open:output_type -> neurun.browserservice.v1.OpenResponse
	5,  // 11: neurun.browserservice.v1.BrowserService.Navigate:output_type -> neurun.browserservice.v1.NavigateResponse
	7,  // 12: neurun.browserservice.v1.BrowserService.WaitForNavigation:output_type -> neurun.browserservice.v1.WaitForNavigationResponse
	9,  // 13: neurun.browserservice.v1.BrowserService.GetCookies:output_type -> neurun.browserservice.v1.GetCookiesResponse
	11, // 14: neurun.browserservice.v1.BrowserService.SetCookies:output_type -> neurun.browserservice.v1.SetCookiesResponse
	13, // 15: neurun.browserservice.v1.BrowserService.Close:output_type -> neurun.browserservice.v1.CloseResponse
	14, // 16: neurun.browserservice.v1.BrowserService.StreamDisplay:output_type -> neurun.browserservice.v1.DisplayChunk
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_browserservice_proto_init() }
func file_proto_browserservice_proto_init() {
	if File_proto_browserservice_proto != nil {
		return
	}
	file_proto_browserservice_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_browserservice_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_browserservice_proto_rawDesc), len(file_proto_browserservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_browserservice_proto_goTypes,
		DependencyIndexes: file_proto_browserservice_proto_depIdxs,
		EnumInfos:         file_proto_browserservice_proto_enumTypes,
		MessageInfos:      file_proto_browserservice_proto_msgTypes,
	}.Build()
	File_proto_browserservice_proto = out.File
	file_proto_browserservice_proto_goTypes = nil
	file_proto_browserservice_proto_depIdxs = nil
}
