// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/browserservice.proto

package browserservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrowserService_Open_FullMethodName              = "/neurun.browserservice.v1.BrowserService/Open"
	BrowserService_Navigate_FullMethodName          = "/neurun.browserservice.v1.BrowserService/Navigate"
	BrowserService_WaitForNavigation_FullMethodName = "/neurun.browserservice.v1.BrowserService/WaitForNavigation"
	BrowserService_Close_FullMethodName             = "/neurun.browserservice.v1.BrowserService/Close"
	BrowserService_StreamDisplay_FullMethodName     = "/neurun.browserservice.v1.BrowserService/StreamDisplay"
)

// BrowserServiceClient is the client API for BrowserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrowserService is what neurun-browser serves. The control plane is its only
// client — nothing else knows where it listens, and it is never on a routable
// interface.
//
// It is a separate package from browser.proto rather than a second service in
// it, because they are two different contracts: that one is what tenant code is
// allowed to call, this one is how the control plane talks to a process it
// owns. Sharing a file made it easy to read one as the other.
type BrowserServiceClient interface {
	// Open spawns a browser and returns the session the service minted for it.
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	// Navigate drives a session to a URL.
	Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error)
	// WaitForNavigation blocks until the session's page has navigated.
	WaitForNavigation(ctx context.Context, in *WaitForNavigationRequest, opts ...grpc.CallOption) (*WaitForNavigationResponse, error)
	// Close stops the browser.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	// StreamDisplay is a pipe to the session's framebuffer. Each chunk is opaque
	// RFB: client-to-server frames in, server-to-client frames out.
	//
	// The session is named in the neurun-session-id metadata rather than in every
	// chunk, because it is a property of the stream and not of a frame.
	StreamDisplay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DisplayChunk, DisplayChunk], error)
}

type browserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserServiceClient(cc grpc.ClientConnInterface) BrowserServiceClient {
	return &browserServiceClient{cc}
}

func (c *browserServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, BrowserService_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateResponse)
	err := c.cc.Invoke(ctx, BrowserService_Navigate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) WaitForNavigation(ctx context.Context, in *WaitForNavigationRequest, opts ...grpc.CallOption) (*WaitForNavigationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForNavigationResponse)
	err := c.cc.Invoke(ctx, BrowserService_WaitForNavigation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, BrowserService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) StreamDisplay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DisplayChunk, DisplayChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrowserService_ServiceDesc.Streams[0], BrowserService_StreamDisplay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DisplayChunk, DisplayChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrowserService_StreamDisplayClient = grpc.BidiStreamingClient[DisplayChunk, DisplayChunk]

// BrowserServiceServer is the server API for BrowserService service.
// All implementations must embed UnimplementedBrowserServiceServer
// for forward compatibility.
//
// BrowserService is what neurun-browser serves. The control plane is its only
// client — nothing else knows where it listens, and it is never on a routable
// interface.
//
// It is a separate package from browser.proto rather than a second service in
// it, because they are two different contracts: that one is what tenant code is
// allowed to call, this one is how the control plane talks to a process it
// owns. Sharing a file made it easy to read one as the other.
type BrowserServiceServer interface {
	// Open spawns a browser and returns the session the service minted for it.
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	// Navigate drives a session to a URL.
	Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error)
	// WaitForNavigation blocks until the session's page has navigated.
	WaitForNavigation(context.Context, *WaitForNavigationRequest) (*WaitForNavigationResponse, error)
	// Close stops the browser.
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	// StreamDisplay is a pipe to the session's framebuffer. Each chunk is opaque
	// RFB: client-to-server frames in, server-to-client frames out.
	//
	// The session is named in the neurun-session-id metadata rather than in every
	// chunk, because it is a property of the stream and not of a frame.
	StreamDisplay(grpc.BidiStreamingServer[DisplayChunk, DisplayChunk]) error
	mustEmbedUnimplementedBrowserServiceServer()
}

// UnimplementedBrowserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserServiceServer struct{}

func (UnimplementedBrowserServiceServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedBrowserServiceServer) Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Navigate not implemented")
}
func (UnimplementedBrowserServiceServer) WaitForNavigation(context.Context, *WaitForNavigationRequest) (*WaitForNavigationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForNavigation not implemented")
}
func (UnimplementedBrowserServiceServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedBrowserServiceServer) StreamDisplay(grpc.BidiStreamingServer[DisplayChunk, DisplayChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDisplay not implemented")
}
func (UnimplementedBrowserServiceServer) mustEmbedUnimplementedBrowserServiceServer() {}
func (UnimplementedBrowserServiceServer) testEmbeddedByValue()                        {}

// UnsafeBrowserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserServiceServer will
// result in compilation errors.
type UnsafeBrowserServiceServer interface {
	mustEmbedUnimplementedBrowserServiceServer()
}

func RegisterBrowserServiceServer(s grpc.ServiceRegistrar, srv BrowserServiceServer) {
	// If the following call pancis, it indicates UnimplementedBrowserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrowserService_ServiceDesc, srv)
}

func _BrowserService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_Navigate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Navigate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Navigate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Navigate(ctx, req.(*NavigateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_WaitForNavigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForNavigationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).WaitForNavigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_WaitForNavigation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).WaitForNavigation(ctx, req.(*WaitForNavigationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_StreamDisplay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrowserServiceServer).StreamDisplay(&grpc.GenericServerStream[DisplayChunk, DisplayChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrowserService_StreamDisplayServer = grpc.BidiStreamingServer[DisplayChunk, DisplayChunk]

// BrowserService_ServiceDesc is the grpc.ServiceDesc for BrowserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrowserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neurun.browserservice.v1.BrowserService",
	HandlerType: (*BrowserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _BrowserService_Open_Handler,
		},
		{
			MethodName: "Navigate",
			Handler:    _BrowserService_Navigate_Handler,
		},
		{
			MethodName: "WaitForNavigation",
			Handler:    _BrowserService_WaitForNavigation_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _BrowserService_Close_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDisplay",
			Handler:       _BrowserService_StreamDisplay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/browserservice.proto",
}
