// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/builder/v1/builder.proto

package builderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Runtime int32

const (
	Runtime_RUNTIME_UNSPECIFIED Runtime = 0
	Runtime_RUNTIME_PYTHON      Runtime = 1
	Runtime_RUNTIME_NODE        Runtime = 2
	Runtime_RUNTIME_GO          Runtime = 3
)

// Enum value maps for Runtime.
var (
	Runtime_name = map[int32]string{
		0: "RUNTIME_UNSPECIFIED",
		1: "RUNTIME_PYTHON",
		2: "RUNTIME_NODE",
		3: "RUNTIME_GO",
	}
	Runtime_value = map[string]int32{
		"RUNTIME_UNSPECIFIED": 0,
		"RUNTIME_PYTHON":      1,
		"RUNTIME_NODE":        2,
		"RUNTIME_GO":          3,
	}
)

func (x Runtime) Enum() *Runtime {
	p := new(Runtime)
	*p = x
	return p
}

func (x Runtime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Runtime) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_builder_v1_builder_proto_enumTypes[0].Descriptor()
}

func (Runtime) Type() protoreflect.EnumType {
	return &file_proto_builder_v1_builder_proto_enumTypes[0]
}

func (x Runtime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Runtime.Descriptor instead.
func (Runtime) EnumDescriptor() ([]byte, []int) {
	return file_proto_builder_v1_builder_proto_rawDescGZIP(), []int{0}
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	SourcePath    string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Runtime       Runtime                `protobuf:"varint,3,opt,name=runtime,proto3,enum=dagflows.builder.v1.Runtime" json:"runtime,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,4,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_proto_builder_v1_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_v1_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_builder_v1_builder_proto_rawDescGZIP(), []int{0}
}

func (x *BuildRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BuildRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *BuildRequest) GetRuntime() Runtime {
	if x != nil {
		return x.Runtime
	}
	return Runtime_RUNTIME_UNSPECIFIED
}

func (x *BuildRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MediaType     string                 `protobuf:"bytes,6,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_proto_builder_v1_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_v1_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_proto_builder_v1_builder_proto_rawDescGZIP(), []int{1}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Artifact) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Artifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Artifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Artifact) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	InstallLayers []*Artifact            `protobuf:"bytes,2,rep,name=install_layers,json=installLayers,proto3" json:"install_layers,omitempty"`
	CodeLayers    []*Artifact            `protobuf:"bytes,3,rep,name=code_layers,json=codeLayers,proto3" json:"code_layers,omitempty"`
	Deployables   []*Artifact            `protobuf:"bytes,4,rep,name=deployables,proto3" json:"deployables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_proto_builder_v1_builder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_v1_builder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_proto_builder_v1_builder_proto_rawDescGZIP(), []int{2}
}

func (x *BuildResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildResponse) GetInstallLayers() []*Artifact {
	if x != nil {
		return x.InstallLayers
	}
	return nil
}

func (x *BuildResponse) GetCodeLayers() []*Artifact {
	if x != nil {
		return x.CodeLayers
	}
	return nil
}

func (x *BuildResponse) GetDeployables() []*Artifact {
	if x != nil {
		return x.Deployables
	}
	return nil
}

var File_proto_builder_v1_builder_proto protoreflect.FileDescriptor

const file_proto_builder_v1_builder_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/builder/v1/builder.proto\x12\x13dagflows.builder.v1\"\x9e\x01\n" +
	"\fBuildRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x126\n" +
	"\aruntime\x18\x03 \x01(\x0e2\x1c.dagflows.builder.v1.RuntimeR\aruntime\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x04 \x01(\tR\n" +
	"entrypoint\"\x9e\x01\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"media_type\x18\x06 \x01(\tR\tmediaType\"\xf1\x01\n" +
	"\rBuildResponse\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12D\n" +
	"\x0einstall_layers\x18\x02 \x03(\v2\x1d.dagflows.builder.v1.ArtifactR\rinstallLayers\x12>\n" +
	"\vcode_layers\x18\x03 \x03(\v2\x1d.dagflows.builder.v1.ArtifactR\n" +
	"codeLayers\x12?\n" +
	"\vdeployables\x18\x04 \x03(\v2\x1d.dagflows.builder.v1.ArtifactR\vdeployables*X\n" +
	"\aRuntime\x12\x17\n" +
	"\x13RUNTIME_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRUNTIME_PYTHON\x10\x01\x12\x10\n" +
	"\fRUNTIME_NODE\x10\x02\x12\x0e\n" +
	"\n" +
	"RUNTIME_GO\x10\x032`\n" +
	"\x0eBuilderService\x12N\n" +
	"\x05Build\x12!.dagflows.builder.v1.BuildRequest\x1a\".dagflows.builder.v1.BuildResponseB8Z6github.com/dagflows/builder/proto/builder/v1;builderv1b\x06proto3"

var (
	file_proto_builder_v1_builder_proto_rawDescOnce sync.Once
	file_proto_builder_v1_builder_proto_rawDescData []byte
)

func file_proto_builder_v1_builder_proto_rawDescGZIP() []byte {
	file_proto_builder_v1_builder_proto_rawDescOnce.Do(func() {
		file_proto_builder_v1_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_builder_v1_builder_proto_rawDesc), len(file_proto_builder_v1_builder_proto_rawDesc)))
	})
	return file_proto_builder_v1_builder_proto_rawDescData
}

var file_proto_builder_v1_builder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_builder_v1_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_builder_v1_builder_proto_goTypes = []any{
	(Runtime)(0),          // 0: dagflows.builder.v1.Runtime
	(*BuildRequest)(nil),  // 1: dagflows.builder.v1.BuildRequest
	(*Artifact)(nil),      // 2: dagflows.builder.v1.Artifact
	(*BuildResponse)(nil), // 3: dagflows.builder.v1.BuildResponse
}
var file_proto_builder_v1_builder_proto_depIdxs = []int32{
	0, // 0: dagflows.builder.v1.BuildRequest.runtime:type_name -> dagflows.builder.v1.Runtime
	2, // 1: dagflows.builder.v1.BuildResponse.install_layers:type_name -> dagflows.builder.v1.Artifact
	2, // 2: dagflows.builder.v1.BuildResponse.code_layers:type_name -> dagflows.builder.v1.Artifact
	2, // 3: dagflows.builder.v1.BuildResponse.deployables:type_name -> dagflows.builder.v1.Artifact
	1, // 4: dagflows.builder.v1.BuilderService.Build:input_type -> dagflows.builder.v1.BuildRequest
	3, // 5: dagflows.builder.v1.BuilderService.Build:output_type -> dagflows.builder.v1.BuildResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_builder_v1_builder_proto_init() }
func file_proto_builder_v1_builder_proto_init() {
	if File_proto_builder_v1_builder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_builder_v1_builder_proto_rawDesc), len(file_proto_builder_v1_builder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_builder_v1_builder_proto_goTypes,
		DependencyIndexes: file_proto_builder_v1_builder_proto_depIdxs,
		EnumInfos:         file_proto_builder_v1_builder_proto_enumTypes,
		MessageInfos:      file_proto_builder_v1_builder_proto_msgTypes,
	}.Build()
	File_proto_builder_v1_builder_proto = out.File
	file_proto_builder_v1_builder_proto_goTypes = nil
	file_proto_builder_v1_builder_proto_depIdxs = nil
}
