-- Neurun control-plane source-of-truth schema.
-- IDs are generated by the application as prefixed ULID-compatible strings.

BEGIN;

CREATE TABLE organizations (
    id              text PRIMARY KEY,
    name            text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT organizations_name_nonempty CHECK (length(btrim(name)) > 0)
);

CREATE TABLE projects (
    id              text PRIMARY KEY,
    organization_id text NOT NULL REFERENCES organizations(id),
    name            text NOT NULL,
    retention       jsonb NOT NULL DEFAULT '{}'::jsonb,
    quotas          jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, name)
);

CREATE TABLE api_keys (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES projects(id),
    name            text NOT NULL,
    key_prefix      text NOT NULL,
    key_hash        bytea NOT NULL,
    scopes          text[] NOT NULL DEFAULT '{}',
    expires_at      timestamptz,
    last_used_at    timestamptz,
    revoked_at      timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (key_prefix),
    CONSTRAINT api_keys_hash_nonempty CHECK (octet_length(key_hash) >= 32)
);

-- Human logins for the operator dashboard. Distinct from api_keys, which
-- authenticate a program: an operator is a person, carries a role rather than an
-- explicit scope list, and signs in with a password.
CREATE TABLE operators (
    id              text PRIMARY KEY,
    organization_id text NOT NULL REFERENCES organizations(id),
    username        text NOT NULL,
    role            text NOT NULL,
    -- Encoded PBKDF2-HMAC-SHA256 hash, self-describing so the iteration count
    -- can be raised without invalidating existing rows.
    password_hash   text NOT NULL,
    disabled_at     timestamptz,
    last_login_at   timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, username),
    CONSTRAINT operators_username_normalized
        CHECK (username = lower(btrim(username)) AND length(username) > 0),
    CONSTRAINT operators_role_known
        CHECK (role IN ('admin', 'operator', 'viewer')),
    CONSTRAINT operators_password_hash_encoded
        CHECK (password_hash LIKE 'pbkdf2-sha256$%')
);

-- Issued operator sign-ins. Named operator_sessions to keep it clearly separate
-- from `sessions`, which holds browser sessions for scraping work.
--
-- Only the SHA-256 digest of the token is stored, so a dump of this table cannot
-- be replayed as a live cookie.
CREATE TABLE operator_sessions (
    id              text PRIMARY KEY,
    operator_id     text NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
    project_id      text REFERENCES projects(id),
    token_hash      bytea NOT NULL,
    user_agent      text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    expires_at      timestamptz NOT NULL,
    revoked_at      timestamptz,
    UNIQUE (token_hash),
    CONSTRAINT operator_sessions_token_hash_length
        CHECK (octet_length(token_hash) = 32),
    CONSTRAINT operator_sessions_expiry_after_creation
        CHECK (expires_at > created_at)
);

CREATE INDEX operator_sessions_operator_expiry
    ON operator_sessions(operator_id, expires_at DESC);

-- Supports pruning expired sessions without scanning revoked ones.
CREATE INDEX operator_sessions_live_expiry
    ON operator_sessions(expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE function_definitions (
    name            text PRIMARY KEY,
    category        text NOT NULL,
    description     text NOT NULL DEFAULT '',
    status          text NOT NULL DEFAULT 'active',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT function_definitions_status CHECK (status IN ('active', 'deprecated', 'disabled'))
);

CREATE TABLE function_versions (
    function_name   text NOT NULL REFERENCES function_definitions(name),
    version         text NOT NULL,
    digest          text NOT NULL,
    manifest        jsonb NOT NULL,
    bundle_version  text NOT NULL,
    installed_at    timestamptz NOT NULL DEFAULT now(),
    deprecated_at   timestamptz,
    PRIMARY KEY (function_name, version),
    UNIQUE (digest),
    CONSTRAINT function_versions_digest CHECK (digest ~ '^sha256:[0-9a-f]{64}$')
);

CREATE TABLE function_aliases (
    function_name   text NOT NULL REFERENCES function_definitions(name),
    alias           text NOT NULL,
    version         text NOT NULL,
    digest          text NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (function_name, alias),
    FOREIGN KEY (function_name, version)
        REFERENCES function_versions(function_name, version)
);

CREATE TABLE jobs (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES projects(id),
    kind                text NOT NULL,
    status              text NOT NULL,
    spec                jsonb NOT NULL,
    resolved_functions  jsonb NOT NULL DEFAULT '[]'::jsonb,
    idempotency_key     text,
    priority            smallint NOT NULL DEFAULT 0,
    retry_policy        jsonb NOT NULL DEFAULT '{}'::jsonb,
    scheduled_for       timestamptz,
    next_attempt_at     timestamptz,
    cancel_requested_at timestamptz,
    terminal_at         timestamptz,
    trace_id            text NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT jobs_status CHECK (
        status IN (
            'accepted', 'queued', 'leased', 'running', 'retry_wait',
            'succeeded', 'rejected', 'failed', 'canceled', 'dead_lettered'
        )
    ),
    CONSTRAINT jobs_kind CHECK (kind IN ('function', 'fetch', 'workflow', 'session'))
);

CREATE UNIQUE INDEX jobs_project_idempotency
    ON jobs(project_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX jobs_dispatchable
    ON jobs(status, next_attempt_at, priority DESC, created_at)
    WHERE status IN ('accepted', 'queued', 'retry_wait');
CREATE INDEX jobs_project_created
    ON jobs(project_id, created_at DESC, id DESC);

CREATE TABLE job_attempts (
    id                  text PRIMARY KEY,
    job_id              text NOT NULL REFERENCES jobs(id),
    attempt_number      integer NOT NULL,
    agent_id            text,
    status              text NOT NULL,
    mode                text,
    lease_token_hash    bytea,
    lease_expires_at    timestamptz,
    started_at          timestamptz,
    finished_at         timestamptz,
    failure_category    text,
    failure             jsonb,
    usage               jsonb NOT NULL DEFAULT '{}'::jsonb,
    trace_id            text NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (job_id, attempt_number),
    CONSTRAINT job_attempts_status CHECK (
        status IN ('leased', 'running', 'succeeded', 'rejected', 'failed', 'canceled', 'lost')
    ),
    CONSTRAINT job_attempts_lease_pair CHECK (
        (lease_token_hash IS NULL) = (lease_expires_at IS NULL)
    )
);

CREATE INDEX job_attempts_active_leases
    ON job_attempts(lease_expires_at)
    WHERE status IN ('leased', 'running');

CREATE TABLE job_events (
    sequence        bigserial PRIMARY KEY,
    id              text NOT NULL UNIQUE,
    project_id      text NOT NULL REFERENCES projects(id),
    job_id          text NOT NULL REFERENCES jobs(id),
    attempt_id      text REFERENCES job_attempts(id),
    type            text NOT NULL,
    data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    trace_id        text NOT NULL,
    occurred_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX job_events_job_sequence ON job_events(job_id, sequence);
CREATE INDEX job_events_project_time ON job_events(project_id, occurred_at DESC);

CREATE TABLE function_invocations (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES projects(id),
    job_id              text REFERENCES jobs(id),
    attempt_id          text REFERENCES job_attempts(id),
    session_id          text,
    workflow_step       text,
    function_name       text NOT NULL,
    function_version    text NOT NULL,
    function_digest     text NOT NULL,
    status              text NOT NULL,
    input_hash          text NOT NULL,
    input_summary       jsonb NOT NULL DEFAULT '{}'::jsonb,
    output              jsonb,
    failure_category    text,
    failure             jsonb,
    usage               jsonb NOT NULL DEFAULT '{}'::jsonb,
    trace_id            text NOT NULL,
    span_id             text NOT NULL,
    started_at          timestamptz,
    finished_at         timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (function_name, function_version)
        REFERENCES function_versions(function_name, version),
    CONSTRAINT function_invocations_status CHECK (
        status IN ('accepted', 'queued', 'running', 'succeeded', 'rejected', 'failed', 'canceled')
    )
);

CREATE INDEX function_invocations_project_time
    ON function_invocations(project_id, created_at DESC);
CREATE INDEX function_invocations_job
    ON function_invocations(job_id, created_at);

CREATE TABLE outbox (
    id                  text PRIMARY KEY,
    aggregate_type      text NOT NULL,
    aggregate_id        text NOT NULL,
    topic               text NOT NULL,
    message_id          text NOT NULL UNIQUE,
    payload             jsonb NOT NULL,
    attempts            integer NOT NULL DEFAULT 0,
    available_at        timestamptz NOT NULL DEFAULT now(),
    claimed_by          text,
    claim_expires_at    timestamptz,
    published_at        timestamptz,
    last_error          text,
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX outbox_unpublished
    ON outbox(available_at, created_at)
    WHERE published_at IS NULL;

CREATE TABLE agents (
    id                  text PRIMARY KEY,
    bootstrap_identity  text NOT NULL UNIQUE,
    version             text NOT NULL,
    labels              jsonb NOT NULL DEFAULT '{}'::jsonb,
    capabilities        text[] NOT NULL DEFAULT '{}',
    function_bundle     text NOT NULL,
    capacity            jsonb NOT NULL DEFAULT '{}'::jsonb,
    usage               jsonb NOT NULL DEFAULT '{}'::jsonb,
    drain_requested_at  timestamptz,
    last_heartbeat_at   timestamptz NOT NULL,
    registered_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX agents_heartbeat ON agents(last_heartbeat_at DESC);

CREATE TABLE identities (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES projects(id),
    name            text NOT NULL,
    current_version integer NOT NULL DEFAULT 1,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    UNIQUE (project_id, name)
);

CREATE TABLE identity_versions (
    identity_id     text NOT NULL REFERENCES identities(id),
    version         integer NOT NULL,
    definition      jsonb NOT NULL,
    digest          text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (identity_id, version)
);

CREATE TABLE profiles (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES projects(id),
    name            text NOT NULL,
    current_version integer NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    UNIQUE (project_id, name)
);

CREATE TABLE profile_versions (
    profile_id          text NOT NULL REFERENCES profiles(id),
    version             integer NOT NULL,
    encryption_key_id   text NOT NULL,
    ciphertext          bytea NOT NULL,
    plaintext_sha256    text NOT NULL,
    source_attempt_id   text REFERENCES job_attempts(id),
    created_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, version)
);

CREATE TABLE proxies (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES projects(id),
    name                text NOT NULL,
    protocol            text NOT NULL,
    endpoint_ciphertext bytea NOT NULL,
    encryption_key_id   text NOT NULL,
    labels              jsonb NOT NULL DEFAULT '{}'::jsonb,
    concurrency_limit   integer NOT NULL DEFAULT 1,
    health              text NOT NULL DEFAULT 'unknown',
    quarantined_until   timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    deleted_at          timestamptz,
    UNIQUE (project_id, name),
    CONSTRAINT proxies_protocol CHECK (protocol IN ('http', 'https', 'socks5')),
    CONSTRAINT proxies_concurrency CHECK (concurrency_limit > 0)
);

CREATE TABLE proxy_observations (
    sequence        bigserial PRIMARY KEY,
    proxy_id        text NOT NULL REFERENCES proxies(id),
    project_id      text NOT NULL REFERENCES projects(id),
    target_host     text NOT NULL,
    outcome         text NOT NULL,
    latency_ms      integer,
    status_code     integer,
    failure_category text,
    observed_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX proxy_observations_recent
    ON proxy_observations(proxy_id, target_host, observed_at DESC);

CREATE TABLE sessions (
    id                      text PRIMARY KEY,
    project_id              text NOT NULL REFERENCES projects(id),
    job_id                  text REFERENCES jobs(id),
    agent_id                text REFERENCES agents(id),
    status                  text NOT NULL,
    browser                 jsonb NOT NULL,
    identity_id             text REFERENCES identities(id),
    identity_version        integer,
    profile_id              text REFERENCES profiles(id),
    profile_version         integer,
    profile_mode            text,
    proxy_id                text REFERENCES proxies(id),
    cdp_token_hash          bytea,
    reconnect_token_hash    bytea,
    resource_limits         jsonb NOT NULL DEFAULT '{}'::jsonb,
    reconnect_grace_seconds integer NOT NULL,
    expires_at              timestamptz NOT NULL,
    last_connected_at       timestamptz,
    closed_at               timestamptz,
    close_reason            text,
    trace_id                text NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT sessions_status CHECK (
        status IN ('provisioning', 'ready', 'connected', 'disconnected', 'closing', 'closed', 'crashed', 'expired')
    )
);

CREATE INDEX sessions_expiry
    ON sessions(expires_at)
    WHERE status NOT IN ('closed', 'crashed', 'expired');
CREATE INDEX sessions_project_time
    ON sessions(project_id, created_at DESC);

ALTER TABLE function_invocations
    ADD CONSTRAINT function_invocations_session
    FOREIGN KEY (session_id) REFERENCES sessions(id);

CREATE TABLE session_usage_samples (
    session_id          text NOT NULL REFERENCES sessions(id),
    sequence            bigint NOT NULL,
    observed_at         timestamptz NOT NULL,
    state               text NOT NULL,
    cpu                 jsonb NOT NULL DEFAULT '{}'::jsonb,
    memory              jsonb NOT NULL DEFAULT '{}'::jsonb,
    processes           jsonb NOT NULL DEFAULT '{}'::jsonb,
    network             jsonb NOT NULL DEFAULT '{}'::jsonb,
    uptime_seconds      double precision NOT NULL DEFAULT 0,
    events              jsonb NOT NULL DEFAULT '[]'::jsonb,
    PRIMARY KEY (session_id, sequence)
);

CREATE INDEX session_usage_time
    ON session_usage_samples(session_id, observed_at DESC);

CREATE TABLE artifacts (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES projects(id),
    job_id              text REFERENCES jobs(id),
    attempt_id          text REFERENCES job_attempts(id),
    invocation_id       text REFERENCES function_invocations(id),
    session_id          text REFERENCES sessions(id),
    kind                text NOT NULL,
    media_type          text NOT NULL,
    bucket              text NOT NULL,
    object_key          text NOT NULL,
    sha256              text NOT NULL,
    size_bytes          bigint NOT NULL,
    redaction           jsonb NOT NULL DEFAULT '{}'::jsonb,
    expires_at          timestamptz,
    deleted_at          timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (bucket, object_key),
    CONSTRAINT artifacts_sha256 CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT artifacts_size CHECK (size_bytes >= 0)
);

CREATE INDEX artifacts_project_time
    ON artifacts(project_id, created_at DESC);
CREATE INDEX artifacts_expiry
    ON artifacts(expires_at)
    WHERE deleted_at IS NULL;

CREATE TABLE webhooks (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES projects(id),
    url                 text NOT NULL,
    events              text[] NOT NULL,
    secret_ciphertext   bytea NOT NULL,
    encryption_key_id   text NOT NULL,
    enabled             boolean NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE webhook_deliveries (
    id                  text PRIMARY KEY,
    webhook_id          text NOT NULL REFERENCES webhooks(id),
    event_id            text NOT NULL,
    attempt             integer NOT NULL,
    status              text NOT NULL,
    response_status     integer,
    response_body       text,
    next_attempt_at     timestamptz,
    delivered_at        timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (webhook_id, event_id, attempt)
);

CREATE INDEX webhook_deliveries_retry
    ON webhook_deliveries(next_attempt_at)
    WHERE delivered_at IS NULL;

CREATE TABLE schedules (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES projects(id),
    name                text NOT NULL,
    cron_expression     text NOT NULL,
    timezone            text NOT NULL,
    enabled             boolean NOT NULL DEFAULT true,
    current_version     integer NOT NULL DEFAULT 1,
    next_run_at         timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, name)
);

CREATE TABLE schedule_versions (
    schedule_id         text NOT NULL REFERENCES schedules(id),
    version             integer NOT NULL,
    job_template        jsonb NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (schedule_id, version)
);

CREATE TABLE audit_events (
    sequence            bigserial PRIMARY KEY,
    id                  text NOT NULL UNIQUE,
    organization_id     text NOT NULL REFERENCES organizations(id),
    project_id          text REFERENCES projects(id),
    actor_type          text NOT NULL,
    actor_id            text,
    action              text NOT NULL,
    resource_type       text NOT NULL,
    resource_id         text,
    request_id          text,
    trace_id            text,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_events_project_time
    ON audit_events(project_id, occurred_at DESC);

CREATE TABLE retention_tombstones (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES projects(id),
    resource_type       text NOT NULL,
    resource_id         text NOT NULL,
    object_key          text,
    state               text NOT NULL,
    attempts            integer NOT NULL DEFAULT 0,
    last_error          text,
    retry_at            timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    completed_at        timestamptz,
    UNIQUE (resource_type, resource_id, object_key)
);

CREATE INDEX retention_tombstones_pending
    ON retention_tombstones(retry_at, created_at)
    WHERE completed_at IS NULL;

COMMIT;

