/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create an account and sign it in. The organization is optional: supply organization_name to start one you own, or invite_token to join one you were invited to, or neither and create or join later. An account may own one organization and join any number. Per-IP limiting belongs at the edge, not in the server. */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Name the organization a token would join, without spending it, so a sign-up page can show it before the account exists. */
        get: operations["lookupInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every organization the signed-in account belongs to. */
        get: operations["listOrganizations"];
        put?: never;
        /** @description Start an organization. Refused with 409 if the account already owns one. The session cookie is re-issued so the new membership is live at once. */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The organization this credential acts in. */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Remove a member. The owner cannot be removed. */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** @description Change a member role. The owner cannot be demoted, so an organization always has somebody who can administer it. */
        patch: operations["updateMember"];
        trace?: never;
    };
    "/v1/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInvites"];
        put?: never;
        /** @description Offer membership to an address. The token is returned exactly once; only its digest is stored. */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Join an organization with an invitation, as an existing account. */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/v1/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApps"];
        put?: never;
        post: operations["createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        get: operations["getApp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateApp"];
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/v1/browser-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBrowserProfiles"];
        put?: never;
        post: operations["createBrowserProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/browser-profiles/{browser_profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                browser_profile_id: string;
            };
            cookie?: never;
        };
        get: operations["getBrowserProfile"];
        put?: never;
        post?: never;
        delete: operations["deleteBrowserProfile"];
        options?: never;
        head?: never;
        patch: operations["updateBrowserProfile"];
        trace?: never;
    };
    "/v1/browser-profiles/{browser_profile_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                browser_profile_id: string;
            };
            cookie?: never;
        };
        /** @description Cookie values and storage contents in the clear — what the SDK reads before it opens a browser on loopback. This is exporting live credentials, so it takes browser_profiles:write rather than :read. */
        get: operations["getBrowserProfileState"];
        /** @description Stores what a closed session captured. A whole-state replace, not a merge: the browser returns its entire cookie jar, so a cookie missing from the body was deleted. */
        put: operations["saveBrowserProfileState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAPIKeys"];
        put?: never;
        post: operations["createAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{api_key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                api_key_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBuilds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/builds/{build_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        get: operations["getBuild"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDeployments"];
        put?: never;
        post: operations["createDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: components["parameters"]["DeploymentID"];
            };
            cookie?: never;
        };
        get: operations["getDeployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: components["parameters"]["DeploymentID"];
            };
            cookie?: never;
        };
        get: operations["listDeploymentExecutions"];
        put?: never;
        post: operations["createDeploymentExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: components["parameters"]["ExecutionID"];
            };
            cookie?: never;
        };
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{execution_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: components["parameters"]["ExecutionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rerunExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Session: {
            user_id: string;
            /** Format: email */
            email: string;
            organization_id: string;
            role: components["schemas"]["Role"];
            scopes: string[];
            session_id: string;
            /** Format: date-time */
            expires_at: string;
        };
        SessionEnvelope: {
            session: components["schemas"]["Session"];
        };
        Project: {
            id: string;
            organization_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        App: {
            id: string;
            project_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        Role: "admin" | "operator" | "viewer";
        User: {
            id: string;
            /** Format: email */
            email: string;
            disabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Organization: {
            id: string;
            name: string;
            owner_user_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Member: {
            user_id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            owner: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Invite: {
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            invited_by?: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "revoked" | "expired";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            accepted_at?: string | null;
        };
        CreatedInvite: components["schemas"]["Invite"] & {
            /** @description Returned exactly once. Only a digest is stored. */
            token: string;
        };
        /** @enum {string} */
        BrowserKind: "chrome" | "firefox";
        /** @description A browser persona. Cookie values and the identity proxy are secrets and are never returned here; GET .../state returns them. */
        BrowserProfile: {
            id: string;
            name: string;
            browser: components["schemas"]["BrowserKind"];
            identity: components["schemas"]["RedactedBrowserIdentity"] | null;
            cookies: components["schemas"]["RedactedCookie"][];
            storage_origins: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Mirrors the rustenium-identity record the browser server applies. */
        BrowserIdentity: {
            /** @description Empty means desktop or laptop. */
            device_model?: string;
            has_battery?: boolean;
            has_mouse?: boolean;
            has_touch?: boolean;
            /** @enum {string} */
            os: "Windows" | "Macintosh" | "Linux" | "Android" | "Ios";
            os_version: string;
            platform: {
                bitness?: string;
                architecture?: string;
                navigator_platform: string;
                version: string;
            };
            /**
             * @description What the browser claims to be, not what it runs on.
             * @enum {string}
             */
            brand: "chrome" | "safari" | "edge";
            browser_version: number[];
            screen: {
                logical_width: number;
                logical_height: number;
                original_width: number;
                original_height: number;
                density_pixel_ratio: number;
            };
            hardware_concurrency: number;
            /** @description deviceMemory in GiB. */
            memory: number;
            gpu: {
                vendor: string;
                webgl_renderer: string;
                webgl_vendor: string;
            };
            /** @enum {string} */
            geo: "US" | "UK" | "JP" | "DE" | "FR" | "CA" | "AU" | "IN" | "BR" | "KR" | "IT" | "ES" | "NL" | "PL" | "SE" | "MX" | "SG" | "ZA";
            language: string[];
            history_count?: number;
            /** @description A full URL with credentials. Write-only: it is never returned. */
            proxy?: string;
            /** @description IANA name; empty resolves via the proxy. */
            timezone?: string;
        };
        RedactedBrowserIdentity: components["schemas"]["BrowserIdentity"] & {
            /** @description Whether a proxy is configured. The URL itself is not returned. */
            proxy_set: boolean;
        };
        /** @description Enough to see what a profile is logged into, and to delete it, without reading the credential. */
        RedactedCookie: {
            name: string;
            domain: string;
            path: string;
            /** @description Unix seconds; absent for a session cookie. */
            expires?: number;
            secure: boolean;
            http_only: boolean;
            same_site?: string;
            value_size: number;
        };
        Cookie: {
            name: string;
            value: string;
            domain: string;
            path: string;
            expires?: number;
            secure: boolean;
            http_only: boolean;
            same_site?: string;
        };
        /** @description Origin to key to value. */
        BrowserStorage: {
            [key: string]: {
                [key: string]: string;
            };
        };
        BrowserProfileState: {
            cookies: components["schemas"]["Cookie"][];
            local_storage: components["schemas"]["BrowserStorage"];
            session_storage: components["schemas"]["BrowserStorage"];
        };
        APIKey: {
            id: string;
            organization_id: string;
            user_id?: string;
            name: string;
            prefix: string;
            scopes: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            revoked_at?: string;
        };
        CreatedAPIKey: components["schemas"]["APIKey"] & {
            secret: string;
        };
        Artifact: {
            id: string;
            kind: string;
            name: string;
            media_type: string;
            /** Format: int64 */
            size_bytes: number;
            sha256: string;
            /** Format: date-time */
            created_at: string;
        };
        Failure: {
            code: string;
            message: string;
        };
        Build: {
            id: string;
            project_id: string;
            deployment_id: string;
            number: number;
            /** @enum {string} */
            status: "building" | "ready" | "failed";
            /** @constant */
            runtime: "python";
            entrypoint: string;
            source_sha256: string;
            artifacts: components["schemas"]["Artifact"][];
            failure?: components["schemas"]["Failure"] | null;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        Deployment: {
            id: string;
            project_id: string;
            app_id: string;
            /** @constant */
            runtime: "python";
            entrypoint: string;
            /** @enum {string} */
            status: "uploaded" | "building" | "ready" | "failed";
            source: components["schemas"]["Artifact"];
            builds: components["schemas"]["Build"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Execution: {
            id: string;
            project_id: string;
            deployment_id: string;
            build_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            input: unknown;
            output?: unknown;
            failure?: components["schemas"]["Failure"] | null;
            logs: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            rerun_of_execution_id?: string;
        };
        Problem: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["Problem"];
        };
    };
    responses: {
        /** @description Request could not be completed. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Limit: number;
        DeploymentID: string;
        ExecutionID: string;
    };
    requestBodies: never;
    headers: {
        Location: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Problem"];
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                        commit: string;
                        built_at: string;
                        api_version: string;
                        schema_version: string;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                    organization_name?: string;
                    invite_token?: string;
                };
            };
        };
        responses: {
            /** @description Account created. The session cookie is set unless sign-in failed, in which case session is absent and the caller signs in normally. member and organization are absent when no organization was named, or when the organization step failed — the account still stands, and the caller starts or joins one afterwards. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                        organization?: components["schemas"]["Organization"];
                        member?: components["schemas"]["Member"];
                        session?: components["schemas"]["Session"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    lookupInvite: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invitation is live. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organization: components["schemas"]["Organization"];
                        /** Format: email */
                        email: string;
                        role: components["schemas"]["Role"];
                    };
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organizations: components["schemas"]["Organization"][];
                    };
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Organization created and the session moved into it. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Organization renamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    listMembers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members of this organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members: components["schemas"]["Member"][];
                    };
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Member updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    listInvites: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitations issued by this organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        invites: components["schemas"]["Invite"][];
                    };
                };
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Invitation created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedInvite"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Membership granted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects visible to the principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects: components["schemas"]["Project"][];
                    };
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Updated project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    listApps: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Return the app with this exact project-scoped name. */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Apps in the authenticated project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apps: components["schemas"]["App"][];
                    };
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    createApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description App created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description App. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description App updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users: components["schemas"]["User"][];
                    };
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    display_name?: string;
                    /** @enum {string} */
                    role?: "admin" | "operator" | "viewer";
                    disabled?: boolean;
                };
            };
        };
        responses: {
            /** @description User updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listBrowserProfiles: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser profiles in the organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        browser_profiles: components["schemas"]["BrowserProfile"][];
                    };
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    createBrowserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    browser: components["schemas"]["BrowserKind"];
                    /** @description Absent launches the browser as itself. */
                    identity?: components["schemas"]["BrowserIdentity"] | null;
                };
            };
        };
        responses: {
            /** @description Profile created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserProfile"];
                };
            };
        };
    };
    getBrowserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                browser_profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserProfile"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteBrowserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                browser_profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    updateBrowserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                browser_profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** @description Null strips the identity; omitted leaves it alone. */
                    identity?: components["schemas"]["BrowserIdentity"] | null;
                };
            };
        };
        responses: {
            /** @description Profile updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserProfile"];
                };
            };
        };
    };
    getBrowserProfileState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                browser_profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserProfileState"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    saveBrowserProfileState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                browser_profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrowserProfileState"];
            };
        };
        responses: {
            /** @description State stored; the profile is returned as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserProfile"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listAPIKeys: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project API keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        api_keys: components["schemas"]["APIKey"][];
                    };
                };
            };
        };
    };
    createAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    user_id?: string;
                    scopes: string[];
                };
            };
        };
        responses: {
            /** @description Key created; secret is returned only here. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedAPIKey"];
                };
            };
        };
    };
    revokeAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                api_key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"];
                };
            };
        };
    };
    listBuilds: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                deployment_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project builds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        builds: components["schemas"]["Build"][];
                    };
                };
            };
        };
    };
    getBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Build"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listDeployments: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Return only deployments owned by this project-scoped App. */
                app_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deployments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deployments: components["schemas"]["Deployment"][];
                    };
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    createDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    app_id: string;
                    /** @constant */
                    runtime: "python";
                    /** @default main.py:handler */
                    entrypoint?: string;
                    /** Format: binary */
                    source: string;
                };
            };
        };
        responses: {
            /** @description Deployment built successfully. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
            401: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: components["parameters"]["DeploymentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listDeploymentExecutions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                deployment_id: components["parameters"]["DeploymentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Executions for this deployment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        executions: components["schemas"]["Execution"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    createDeploymentExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: components["parameters"]["DeploymentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    input: unknown;
                };
            };
        };
        responses: {
            /** @description Execution durably queued and pinned to the latest ready build. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"];
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listExecutions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                deployment_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project executions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        executions: components["schemas"]["Execution"][];
                    };
                };
            };
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: components["parameters"]["ExecutionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    rerunExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: components["parameters"]["ExecutionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New execution queued with the exact original build and input. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
}
