// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/browser.proto

package browserpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WaitUntil is how far into a navigation to wait, mirroring the browser's enum.
type WaitUntil int32

const (
	WaitUntil_WAIT_UNTIL_UNSPECIFIED         WaitUntil = 0
	WaitUntil_WAIT_UNTIL_COMMIT              WaitUntil = 1
	WaitUntil_WAIT_UNTIL_DOM_CONTENT_LOADED  WaitUntil = 2
	WaitUntil_WAIT_UNTIL_LOAD                WaitUntil = 3
	WaitUntil_WAIT_UNTIL_NETWORK_ALMOST_IDLE WaitUntil = 4
	WaitUntil_WAIT_UNTIL_NETWORK_IDLE        WaitUntil = 5
)

// Enum value maps for WaitUntil.
var (
	WaitUntil_name = map[int32]string{
		0: "WAIT_UNTIL_UNSPECIFIED",
		1: "WAIT_UNTIL_COMMIT",
		2: "WAIT_UNTIL_DOM_CONTENT_LOADED",
		3: "WAIT_UNTIL_LOAD",
		4: "WAIT_UNTIL_NETWORK_ALMOST_IDLE",
		5: "WAIT_UNTIL_NETWORK_IDLE",
	}
	WaitUntil_value = map[string]int32{
		"WAIT_UNTIL_UNSPECIFIED":         0,
		"WAIT_UNTIL_COMMIT":              1,
		"WAIT_UNTIL_DOM_CONTENT_LOADED":  2,
		"WAIT_UNTIL_LOAD":                3,
		"WAIT_UNTIL_NETWORK_ALMOST_IDLE": 4,
		"WAIT_UNTIL_NETWORK_IDLE":        5,
	}
)

func (x WaitUntil) Enum() *WaitUntil {
	p := new(WaitUntil)
	*p = x
	return p
}

func (x WaitUntil) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaitUntil) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_browser_proto_enumTypes[0].Descriptor()
}

func (WaitUntil) Type() protoreflect.EnumType {
	return &file_proto_browser_proto_enumTypes[0]
}

func (x WaitUntil) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaitUntil.Descriptor instead.
func (WaitUntil) EnumDescriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{0}
}

type OpenSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chrome or safari. Read only when no profile is named: a profile's identity
	// already says which browser it is, and two answers that could disagree is
	// one answer too many.
	Browser string `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	// The profile to wear. Empty still gets a persona — one is drawn for the
	// session — it just is not kept, along with the cookies it collected.
	BrowserProfileId string `protobuf:"bytes,2,opt,name=browser_profile_id,json=browserProfileId,proto3" json:"browser_profile_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_proto_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSessionRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *OpenSessionRequest) GetBrowserProfileId() string {
	if x != nil {
		return x.BrowserProfileId
	}
	return ""
}

type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId            string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ExecutionId      string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	BrowserProfileId string                 `protobuf:"bytes,4,opt,name=browser_profile_id,json=browserProfileId,proto3" json:"browser_profile_id,omitempty"`
	Browser          string                 `protobuf:"bytes,5,opt,name=browser,proto3" json:"browser,omitempty"`
	// Where the browser runs is never sent. The SDK asks for a session and drives
	// it through this service; a viewer names one and asks the control plane to
	// stream. Neither is told an address, and neither needs one.
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     int64  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Session) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Session) GetBrowserProfileId() string {
	if x != nil {
		return x.BrowserProfileId
	}
	return ""
}

func (x *Session) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

// Every command names its session and is its own message, shaped after the
// browser's own function rather than after anything convenient here. The set is
// small because the browser implements a small set; it grows one command at a
// time, on purpose. A caller can see what it is allowed to do from the service
// definition alone, and a command nobody serves fails to compile rather than at
// runtime.
type NavigateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Url       string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Absent sends no Referer, which is not the same as sending an empty one.
	Referer       *string `protobuf:"bytes,3,opt,name=referer,proto3,oneof" json:"referer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateRequest) Reset() {
	*x = NavigateRequest{}
	mi := &file_proto_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateRequest) ProtoMessage() {}

func (x *NavigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateRequest.ProtoReflect.Descriptor instead.
func (*NavigateRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{2}
}

func (x *NavigateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NavigateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NavigateRequest) GetReferer() string {
	if x != nil && x.Referer != nil {
		return *x.Referer
	}
	return ""
}

type NavigateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateResponse) Reset() {
	*x = NavigateResponse{}
	mi := &file_proto_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateResponse) ProtoMessage() {}

func (x *NavigateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateResponse.ProtoReflect.Descriptor instead.
func (*NavigateResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{3}
}

type WaitForNavigationRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Unspecified is Load, which is the browser's own default.
	WaitUntil WaitUntil `protobuf:"varint,2,opt,name=wait_until,json=waitUntil,proto3,enum=neurun.browser.v1.WaitUntil" json:"wait_until,omitempty"`
	// The browser takes a Duration; this is it in milliseconds, which is as fine
	// as a navigation timeout is ever set. Zero leaves its default in place.
	TimeoutMs     uint32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForNavigationRequest) Reset() {
	*x = WaitForNavigationRequest{}
	mi := &file_proto_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForNavigationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForNavigationRequest) ProtoMessage() {}

func (x *WaitForNavigationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForNavigationRequest.ProtoReflect.Descriptor instead.
func (*WaitForNavigationRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{4}
}

func (x *WaitForNavigationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WaitForNavigationRequest) GetWaitUntil() WaitUntil {
	if x != nil {
		return x.WaitUntil
	}
	return WaitUntil_WAIT_UNTIL_UNSPECIFIED
}

func (x *WaitForNavigationRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WaitForNavigationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForNavigationResponse) Reset() {
	*x = WaitForNavigationResponse{}
	mi := &file_proto_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForNavigationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForNavigationResponse) ProtoMessage() {}

func (x *WaitForNavigationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForNavigationResponse.ProtoReflect.Descriptor instead.
func (*WaitForNavigationResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{5}
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_proto_browser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{6}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_proto_browser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{7}
}

var File_proto_browser_proto protoreflect.FileDescriptor

const file_proto_browser_proto_rawDesc = "" +
	"\n" +
	"\x13proto/browser.proto\x12\x11neurun.browser.v1\"\\\n" +
	"\x12OpenSessionRequest\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12,\n" +
	"\x12browser_profile_id\x18\x02 \x01(\tR\x10browserProfileId\"\xd2\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12,\n" +
	"\x12browser_profile_id\x18\x04 \x01(\tR\x10browserProfileId\x12\x18\n" +
	"\abrowser\x18\x05 \x01(\tR\abrowser\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\"m\n" +
	"\x0fNavigateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\areferer\x18\x03 \x01(\tH\x00R\areferer\x88\x01\x01B\n" +
	"\n" +
	"\b_referer\"\x12\n" +
	"\x10NavigateResponse\"\x95\x01\n" +
	"\x18WaitForNavigationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\n" +
	"wait_until\x18\x02 \x01(\x0e2\x1c.neurun.browser.v1.WaitUntilR\twaitUntil\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\"\x1b\n" +
	"\x19WaitForNavigationResponse\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse*\xb7\x01\n" +
	"\tWaitUntil\x12\x1a\n" +
	"\x16WAIT_UNTIL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WAIT_UNTIL_COMMIT\x10\x01\x12!\n" +
	"\x1dWAIT_UNTIL_DOM_CONTENT_LOADED\x10\x02\x12\x13\n" +
	"\x0fWAIT_UNTIL_LOAD\x10\x03\x12\"\n" +
	"\x1eWAIT_UNTIL_NETWORK_ALMOST_IDLE\x10\x04\x12\x1b\n" +
	"\x17WAIT_UNTIL_NETWORK_IDLE\x10\x052\x81\x03\n" +
	"\aBrowser\x12P\n" +
	"\vOpenSession\x12%.neurun.browser.v1.OpenSessionRequest\x1a\x1a.neurun.browser.v1.Session\x12S\n" +
	"\bNavigate\x12\".neurun.browser.v1.NavigateRequest\x1a#.neurun.browser.v1.NavigateResponse\x12n\n" +
	"\x11WaitForNavigation\x12+.neurun.browser.v1.WaitForNavigationRequest\x1a,.neurun.browser.v1.WaitForNavigationResponse\x12_\n" +
	"\fCloseSession\x12&.neurun.browser.v1.CloseSessionRequest\x1a'.neurun.browser.v1.CloseSessionResponseB:Z8github.com/neurun-io/neurun/internal/browserpb;browserpbb\x06proto3"

var (
	file_proto_browser_proto_rawDescOnce sync.Once
	file_proto_browser_proto_rawDescData []byte
)

func file_proto_browser_proto_rawDescGZIP() []byte {
	file_proto_browser_proto_rawDescOnce.Do(func() {
		file_proto_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_browser_proto_rawDesc), len(file_proto_browser_proto_rawDesc)))
	})
	return file_proto_browser_proto_rawDescData
}

var file_proto_browser_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_browser_proto_goTypes = []any{
	(WaitUntil)(0),                    // 0: neurun.browser.v1.WaitUntil
	(*OpenSessionRequest)(nil),        // 1: neurun.browser.v1.OpenSessionRequest
	(*Session)(nil),                   // 2: neurun.browser.v1.Session
	(*NavigateRequest)(nil),           // 3: neurun.browser.v1.NavigateRequest
	(*NavigateResponse)(nil),          // 4: neurun.browser.v1.NavigateResponse
	(*WaitForNavigationRequest)(nil),  // 5: neurun.browser.v1.WaitForNavigationRequest
	(*WaitForNavigationResponse)(nil), // 6: neurun.browser.v1.WaitForNavigationResponse
	(*CloseSessionRequest)(nil),       // 7: neurun.browser.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil),      // 8: neurun.browser.v1.CloseSessionResponse
}
var file_proto_browser_proto_depIdxs = []int32{
	0, // 0: neurun.browser.v1.WaitForNavigationRequest.wait_until:type_name -> neurun.browser.v1.WaitUntil
	1, // 1: neurun.browser.v1.Browser.OpenSession:input_type -> neurun.browser.v1.OpenSessionRequest
	3, // 2: neurun.browser.v1.Browser.Navigate:input_type -> neurun.browser.v1.NavigateRequest
	5, // 3: neurun.browser.v1.Browser.WaitForNavigation:input_type -> neurun.browser.v1.WaitForNavigationRequest
	7, // 4: neurun.browser.v1.Browser.CloseSession:input_type -> neurun.browser.v1.CloseSessionRequest
	2, // 5: neurun.browser.v1.Browser.OpenSession:output_type -> neurun.browser.v1.Session
	4, // 6: neurun.browser.v1.Browser.Navigate:output_type -> neurun.browser.v1.NavigateResponse
	6, // 7: neurun.browser.v1.Browser.WaitForNavigation:output_type -> neurun.browser.v1.WaitForNavigationResponse
	8, // 8: neurun.browser.v1.Browser.CloseSession:output_type -> neurun.browser.v1.CloseSessionResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_browser_proto_init() }
func file_proto_browser_proto_init() {
	if File_proto_browser_proto != nil {
		return
	}
	file_proto_browser_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_browser_proto_rawDesc), len(file_proto_browser_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_browser_proto_goTypes,
		DependencyIndexes: file_proto_browser_proto_depIdxs,
		EnumInfos:         file_proto_browser_proto_enumTypes,
		MessageInfos:      file_proto_browser_proto_msgTypes,
	}.Build()
	File_proto_browser_proto = out.File
	file_proto_browser_proto_goTypes = nil
	file_proto_browser_proto_depIdxs = nil
}
