// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: browser.proto

package browserpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chrome or firefox.
	Browser string `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	// The profile to wear. Empty is a plain browser, which is the ordinary case.
	BrowserProfileId string `protobuf:"bytes,2,opt,name=browser_profile_id,json=browserProfileId,proto3" json:"browser_profile_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSessionRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *OpenSessionRequest) GetBrowserProfileId() string {
	if x != nil {
		return x.BrowserProfileId
	}
	return ""
}

type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId            string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ExecutionId      string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	BrowserProfileId string                 `protobuf:"bytes,4,opt,name=browser_profile_id,json=browserProfileId,proto3" json:"browser_profile_id,omitempty"`
	Browser          string                 `protobuf:"bytes,5,opt,name=browser,proto3" json:"browser,omitempty"`
	// Where the browser runs is never sent. The SDK asks for a session and drives
	// it through this service; a viewer names one and asks the control plane to
	// stream. Neither is told an address, and neither needs one.
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     int64  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Session) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Session) GetBrowserProfileId() string {
	if x != nil {
		return x.BrowserProfileId
	}
	return ""
}

func (x *Session) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type ExecuteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// A serialized browser-service command. Neither the SDK's encoding nor the
	// browser service's is this service's business.
	Command       []byte `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{4}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{5}
}

type OpenRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Browser          string                 `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserProfileId string                 `protobuf:"bytes,2,opt,name=browser_profile_id,json=browserProfileId,proto3" json:"browser_profile_id,omitempty"`
	AppId            string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ExecutionId      string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_browser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{6}
}

func (x *OpenRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *OpenRequest) GetBrowserProfileId() string {
	if x != nil {
		return x.BrowserProfileId
	}
	return ""
}

func (x *OpenRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *OpenRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_browser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{7}
}

func (x *OpenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       []byte                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_browser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{8}
}

func (x *RunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_browser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{9}
}

func (x *RunResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_browser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{10}
}

func (x *CloseRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_browser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{11}
}

type DisplayChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayChunk) Reset() {
	*x = DisplayChunk{}
	mi := &file_browser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayChunk) ProtoMessage() {}

func (x *DisplayChunk) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayChunk.ProtoReflect.Descriptor instead.
func (*DisplayChunk) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{12}
}

func (x *DisplayChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_browser_proto protoreflect.FileDescriptor

const file_browser_proto_rawDesc = "" +
	"\n" +
	"\rbrowser.proto\x12\x11neurun.browser.v1\"\\\n" +
	"\x12OpenSessionRequest\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12,\n" +
	"\x12browser_profile_id\x18\x02 \x01(\tR\x10browserProfileId\"\xd2\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12,\n" +
	"\x12browser_profile_id\x18\x04 \x01(\tR\x10browserProfileId\x12\x18\n" +
	"\abrowser\x18\x05 \x01(\tR\abrowser\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\"I\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\fR\acommand\")\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\"\x8f\x01\n" +
	"\vOpenRequest\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12,\n" +
	"\x12browser_profile_id\x18\x02 \x01(\tR\x10browserProfileId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\"-\n" +
	"\fOpenResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\n" +
	"RunRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\fR\acommand\"%\n" +
	"\vRunResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"-\n" +
	"\fCloseRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x0f\n" +
	"\rCloseResponse\"\"\n" +
	"\fDisplayChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x8e\x02\n" +
	"\aBrowser\x12P\n" +
	"\vOpenSession\x12%.neurun.browser.v1.OpenSessionRequest\x1a\x1a.neurun.browser.v1.Session\x12P\n" +
	"\aExecute\x12!.neurun.browser.v1.ExecuteRequest\x1a\".neurun.browser.v1.ExecuteResponse\x12_\n" +
	"\fCloseSession\x12&.neurun.browser.v1.CloseSessionRequest\x1a'.neurun.browser.v1.CloseSessionResponse2\xc2\x02\n" +
	"\x0eBrowserService\x12G\n" +
	"\x04Open\x12\x1e.neurun.browser.v1.OpenRequest\x1a\x1f.neurun.browser.v1.OpenResponse\x12D\n" +
	"\x03Run\x12\x1d.neurun.browser.v1.RunRequest\x1a\x1e.neurun.browser.v1.RunResponse\x12J\n" +
	"\x05Close\x12\x1f.neurun.browser.v1.CloseRequest\x1a .neurun.browser.v1.CloseResponse\x12U\n" +
	"\rStreamDisplay\x12\x1f.neurun.browser.v1.DisplayChunk\x1a\x1f.neurun.browser.v1.DisplayChunk(\x010\x01B:Z8github.com/neurun-io/neurun/internal/browserpb;browserpbb\x06proto3"

var (
	file_browser_proto_rawDescOnce sync.Once
	file_browser_proto_rawDescData []byte
)

func file_browser_proto_rawDescGZIP() []byte {
	file_browser_proto_rawDescOnce.Do(func() {
		file_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_browser_proto_rawDesc), len(file_browser_proto_rawDesc)))
	})
	return file_browser_proto_rawDescData
}

var file_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_browser_proto_goTypes = []any{
	(*OpenSessionRequest)(nil),   // 0: neurun.browser.v1.OpenSessionRequest
	(*Session)(nil),              // 1: neurun.browser.v1.Session
	(*ExecuteRequest)(nil),       // 2: neurun.browser.v1.ExecuteRequest
	(*ExecuteResponse)(nil),      // 3: neurun.browser.v1.ExecuteResponse
	(*CloseSessionRequest)(nil),  // 4: neurun.browser.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil), // 5: neurun.browser.v1.CloseSessionResponse
	(*OpenRequest)(nil),          // 6: neurun.browser.v1.OpenRequest
	(*OpenResponse)(nil),         // 7: neurun.browser.v1.OpenResponse
	(*RunRequest)(nil),           // 8: neurun.browser.v1.RunRequest
	(*RunResponse)(nil),          // 9: neurun.browser.v1.RunResponse
	(*CloseRequest)(nil),         // 10: neurun.browser.v1.CloseRequest
	(*CloseResponse)(nil),        // 11: neurun.browser.v1.CloseResponse
	(*DisplayChunk)(nil),         // 12: neurun.browser.v1.DisplayChunk
}
var file_browser_proto_depIdxs = []int32{
	0,  // 0: neurun.browser.v1.Browser.OpenSession:input_type -> neurun.browser.v1.OpenSessionRequest
	2,  // 1: neurun.browser.v1.Browser.Execute:input_type -> neurun.browser.v1.ExecuteRequest
	4,  // 2: neurun.browser.v1.Browser.CloseSession:input_type -> neurun.browser.v1.CloseSessionRequest
	6,  // 3: neurun.browser.v1.BrowserService.Open:input_type -> neurun.browser.v1.OpenRequest
	8,  // 4: neurun.browser.v1.BrowserService.Run:input_type -> neurun.browser.v1.RunRequest
	10, // 5: neurun.browser.v1.BrowserService.Close:input_type -> neurun.browser.v1.CloseRequest
	12, // 6: neurun.browser.v1.BrowserService.StreamDisplay:input_type -> neurun.browser.v1.DisplayChunk
	1,  // 7: neurun.browser.v1.Browser.OpenSession:output_type -> neurun.browser.v1.Session
	3,  // 8: neurun.browser.v1.Browser.Execute:output_type -> neurun.browser.v1.ExecuteResponse
	5,  // 9: neurun.browser.v1.Browser.CloseSession:output_type -> neurun.browser.v1.CloseSessionResponse
	7,  // 10: neurun.browser.v1.BrowserService.Open:output_type -> neurun.browser.v1.OpenResponse
	9,  // 11: neurun.browser.v1.BrowserService.Run:output_type -> neurun.browser.v1.RunResponse
	11, // 12: neurun.browser.v1.BrowserService.Close:output_type -> neurun.browser.v1.CloseResponse
	12, // 13: neurun.browser.v1.BrowserService.StreamDisplay:output_type -> neurun.browser.v1.DisplayChunk
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_browser_proto_init() }
func file_browser_proto_init() {
	if File_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_browser_proto_rawDesc), len(file_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_browser_proto_goTypes,
		DependencyIndexes: file_browser_proto_depIdxs,
		MessageInfos:      file_browser_proto_msgTypes,
	}.Build()
	File_browser_proto = out.File
	file_browser_proto_goTypes = nil
	file_browser_proto_depIdxs = nil
}
