// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: browser.proto

package browserpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Browser_OpenSession_FullMethodName  = "/neurun.browser.v1.Browser/OpenSession"
	Browser_Execute_FullMethodName      = "/neurun.browser.v1.Browser/Execute"
	Browser_CloseSession_FullMethodName = "/neurun.browser.v1.Browser/CloseSession"
)

// BrowserClient is the client API for Browser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Browser is what the SDK talks to. It is served by the control plane on
// loopback inside the worker, never on a routable interface.
//
// The SDK does not know where a browser actually runs and cannot be told. It
// asks for one; the control plane spawns a browser service in the worker
// environment, keeps the handle, and relays. That is what makes a session
// something the dashboard can list and watch — nothing is happening on a port
// only the tenant's code knows about.
type BrowserClient interface {
	// OpenSession spawns a browser and returns the session it created.
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// Execute relays one command to the session's browser and returns its reply.
	//
	// The payload is opaque on purpose. The control plane brokers sessions, not
	// browser semantics: it never parses a command, so the browser service's
	// command set can grow without a release here, and a command it has never
	// heard of is not a command it can corrupt.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// CloseSession stops the browser and drops the session.
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
}

type browserClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserClient(cc grpc.ClientConnInterface) BrowserClient {
	return &browserClient{cc}
}

func (c *browserClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Browser_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, Browser_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, Browser_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowserServer is the server API for Browser service.
// All implementations must embed UnimplementedBrowserServer
// for forward compatibility.
//
// Browser is what the SDK talks to. It is served by the control plane on
// loopback inside the worker, never on a routable interface.
//
// The SDK does not know where a browser actually runs and cannot be told. It
// asks for one; the control plane spawns a browser service in the worker
// environment, keeps the handle, and relays. That is what makes a session
// something the dashboard can list and watch — nothing is happening on a port
// only the tenant's code knows about.
type BrowserServer interface {
	// OpenSession spawns a browser and returns the session it created.
	OpenSession(context.Context, *OpenSessionRequest) (*Session, error)
	// Execute relays one command to the session's browser and returns its reply.
	//
	// The payload is opaque on purpose. The control plane brokers sessions, not
	// browser semantics: it never parses a command, so the browser service's
	// command set can grow without a release here, and a command it has never
	// heard of is not a command it can corrupt.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// CloseSession stops the browser and drops the session.
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	mustEmbedUnimplementedBrowserServer()
}

// UnimplementedBrowserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserServer struct{}

func (UnimplementedBrowserServer) OpenSession(context.Context, *OpenSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedBrowserServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedBrowserServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedBrowserServer) mustEmbedUnimplementedBrowserServer() {}
func (UnimplementedBrowserServer) testEmbeddedByValue()                 {}

// UnsafeBrowserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserServer will
// result in compilation errors.
type UnsafeBrowserServer interface {
	mustEmbedUnimplementedBrowserServer()
}

func RegisterBrowserServer(s grpc.ServiceRegistrar, srv BrowserServer) {
	// If the following call pancis, it indicates UnimplementedBrowserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Browser_ServiceDesc, srv)
}

func _Browser_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Browser_ServiceDesc is the grpc.ServiceDesc for Browser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Browser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neurun.browser.v1.Browser",
	HandlerType: (*BrowserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _Browser_OpenSession_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Browser_Execute_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _Browser_CloseSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "browser.proto",
}

const (
	BrowserService_Open_FullMethodName          = "/neurun.browser.v1.BrowserService/Open"
	BrowserService_Run_FullMethodName           = "/neurun.browser.v1.BrowserService/Run"
	BrowserService_Close_FullMethodName         = "/neurun.browser.v1.BrowserService/Close"
	BrowserService_StreamDisplay_FullMethodName = "/neurun.browser.v1.BrowserService/StreamDisplay"
)

// BrowserServiceClient is the client API for BrowserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrowserService is what neurun-browser serves. The control plane is its only
// client — nothing else knows where it listens, and it is never on a routable
// interface.
type BrowserServiceClient interface {
	// Open spawns a browser and returns the session the service minted for it.
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	// Run performs one command against a session.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Close stops the browser.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	// StreamDisplay is a pipe to the session's framebuffer. Each chunk is opaque
	// RFB: client-to-server frames in, server-to-client frames out.
	//
	// The session is named in the neurun-session-id metadata rather than in every
	// chunk, because it is a property of the stream and not of a frame.
	StreamDisplay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DisplayChunk, DisplayChunk], error)
}

type browserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserServiceClient(cc grpc.ClientConnInterface) BrowserServiceClient {
	return &browserServiceClient{cc}
}

func (c *browserServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, BrowserService_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, BrowserService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, BrowserService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) StreamDisplay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DisplayChunk, DisplayChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrowserService_ServiceDesc.Streams[0], BrowserService_StreamDisplay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DisplayChunk, DisplayChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrowserService_StreamDisplayClient = grpc.BidiStreamingClient[DisplayChunk, DisplayChunk]

// BrowserServiceServer is the server API for BrowserService service.
// All implementations must embed UnimplementedBrowserServiceServer
// for forward compatibility.
//
// BrowserService is what neurun-browser serves. The control plane is its only
// client — nothing else knows where it listens, and it is never on a routable
// interface.
type BrowserServiceServer interface {
	// Open spawns a browser and returns the session the service minted for it.
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	// Run performs one command against a session.
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Close stops the browser.
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	// StreamDisplay is a pipe to the session's framebuffer. Each chunk is opaque
	// RFB: client-to-server frames in, server-to-client frames out.
	//
	// The session is named in the neurun-session-id metadata rather than in every
	// chunk, because it is a property of the stream and not of a frame.
	StreamDisplay(grpc.BidiStreamingServer[DisplayChunk, DisplayChunk]) error
	mustEmbedUnimplementedBrowserServiceServer()
}

// UnimplementedBrowserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserServiceServer struct{}

func (UnimplementedBrowserServiceServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedBrowserServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedBrowserServiceServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedBrowserServiceServer) StreamDisplay(grpc.BidiStreamingServer[DisplayChunk, DisplayChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDisplay not implemented")
}
func (UnimplementedBrowserServiceServer) mustEmbedUnimplementedBrowserServiceServer() {}
func (UnimplementedBrowserServiceServer) testEmbeddedByValue()                        {}

// UnsafeBrowserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserServiceServer will
// result in compilation errors.
type UnsafeBrowserServiceServer interface {
	mustEmbedUnimplementedBrowserServiceServer()
}

func RegisterBrowserServiceServer(s grpc.ServiceRegistrar, srv BrowserServiceServer) {
	// If the following call pancis, it indicates UnimplementedBrowserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrowserService_ServiceDesc, srv)
}

func _BrowserService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_StreamDisplay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrowserServiceServer).StreamDisplay(&grpc.GenericServerStream[DisplayChunk, DisplayChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrowserService_StreamDisplayServer = grpc.BidiStreamingServer[DisplayChunk, DisplayChunk]

// BrowserService_ServiceDesc is the grpc.ServiceDesc for BrowserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrowserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neurun.browser.v1.BrowserService",
	HandlerType: (*BrowserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _BrowserService_Open_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _BrowserService_Run_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _BrowserService_Close_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDisplay",
			Handler:       _BrowserService_StreamDisplay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "browser.proto",
}
