// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/browser.proto

package browserpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Browser_OpenSession_FullMethodName       = "/neurun.browser.v1.Browser/OpenSession"
	Browser_Navigate_FullMethodName          = "/neurun.browser.v1.Browser/Navigate"
	Browser_WaitForNavigation_FullMethodName = "/neurun.browser.v1.Browser/WaitForNavigation"
	Browser_GetNode_FullMethodName           = "/neurun.browser.v1.Browser/GetNode"
	Browser_HumanMouseMove_FullMethodName    = "/neurun.browser.v1.Browser/HumanMouseMove"
	Browser_HumanMouseClick_FullMethodName   = "/neurun.browser.v1.Browser/HumanMouseClick"
	Browser_HumanType_FullMethodName         = "/neurun.browser.v1.Browser/HumanType"
	Browser_HumanScrollY_FullMethodName      = "/neurun.browser.v1.Browser/HumanScrollY"
	Browser_HumanScrollYTo_FullMethodName    = "/neurun.browser.v1.Browser/HumanScrollYTo"
	Browser_GetCookies_FullMethodName        = "/neurun.browser.v1.Browser/GetCookies"
	Browser_SetCookies_FullMethodName        = "/neurun.browser.v1.Browser/SetCookies"
	Browser_CloseSession_FullMethodName      = "/neurun.browser.v1.Browser/CloseSession"
	Browser_ReportResult_FullMethodName      = "/neurun.browser.v1.Browser/ReportResult"
)

// BrowserClient is the client API for Browser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Browser is what the SDK talks to. It is served by the control plane on
// loopback inside the worker, never on a routable interface.
//
// The SDK does not know where a browser actually runs and cannot be told. It
// asks for one; the control plane spawns a browser service in the worker
// environment, keeps the handle, and relays. That is what makes a session
// something the dashboard can list and watch — nothing is happening on a port
// only the tenant's code knows about.
//
// What neurun-browser serves on the other side is browserservice.proto. The two
// are deliberately separate: this one is a public contract with tenant code, and
// that one is an internal detail nothing outside the host may depend on.
type BrowserClient interface {
	// OpenSession spawns a browser and returns the session it created.
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// Navigate drives the session to a URL.
	Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error)
	// WaitForNavigation blocks until the page the session is on has navigated.
	WaitForNavigation(ctx context.Context, in *WaitForNavigationRequest, opts ...grpc.CallOption) (*WaitForNavigationResponse, error)
	// GetNode reads the first element a selector matches.
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// HumanMouseMove walks the pointer somewhere the way a hand would.
	HumanMouseMove(ctx context.Context, in *HumanMouseMoveRequest, opts ...grpc.CallOption) (*HumanMouseMoveResponse, error)
	// HumanMouseClick walks the pointer somewhere and presses it.
	HumanMouseClick(ctx context.Context, in *HumanMouseClickRequest, opts ...grpc.CallOption) (*HumanMouseClickResponse, error)
	// HumanType types, one key at a time, at a hand's pace.
	HumanType(ctx context.Context, in *HumanTypeRequest, opts ...grpc.CallOption) (*HumanTypeResponse, error)
	// HumanScrollY turns the wheel down the page.
	HumanScrollY(ctx context.Context, in *HumanScrollYRequest, opts ...grpc.CallOption) (*HumanScrollYResponse, error)
	// HumanScrollYTo turns the wheel until an element is where it was asked for.
	HumanScrollYTo(ctx context.Context, in *HumanScrollYToRequest, opts ...grpc.CallOption) (*HumanScrollYToResponse, error)
	// GetCookies reads the session's whole jar.
	//
	// Browser-wide rather than per-origin, because that is what a profile keeps:
	// a partial read written back would delete the rest.
	GetCookies(ctx context.Context, in *GetCookiesRequest, opts ...grpc.CallOption) (*GetCookiesResponse, error)
	// SetCookies puts a jar into the session, on top of what it holds.
	SetCookies(ctx context.Context, in *SetCookiesRequest, opts ...grpc.CallOption) (*SetCookiesResponse, error)
	// CloseSession stops the browser and drops the session.
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	// ReportResult hands back what the app produced.
	//
	// The token says which execution this is, so an app cannot report for another
	// one. Reporting is what produces a result: an execution that exits without
	// reporting produced none, and fails saying so.
	ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*ReportResultResponse, error)
}

type browserClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserClient(cc grpc.ClientConnInterface) BrowserClient {
	return &browserClient{cc}
}

func (c *browserClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Browser_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateResponse)
	err := c.cc.Invoke(ctx, Browser_Navigate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) WaitForNavigation(ctx context.Context, in *WaitForNavigationRequest, opts ...grpc.CallOption) (*WaitForNavigationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForNavigationResponse)
	err := c.cc.Invoke(ctx, Browser_WaitForNavigation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, Browser_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) HumanMouseMove(ctx context.Context, in *HumanMouseMoveRequest, opts ...grpc.CallOption) (*HumanMouseMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HumanMouseMoveResponse)
	err := c.cc.Invoke(ctx, Browser_HumanMouseMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) HumanMouseClick(ctx context.Context, in *HumanMouseClickRequest, opts ...grpc.CallOption) (*HumanMouseClickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HumanMouseClickResponse)
	err := c.cc.Invoke(ctx, Browser_HumanMouseClick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) HumanType(ctx context.Context, in *HumanTypeRequest, opts ...grpc.CallOption) (*HumanTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HumanTypeResponse)
	err := c.cc.Invoke(ctx, Browser_HumanType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) HumanScrollY(ctx context.Context, in *HumanScrollYRequest, opts ...grpc.CallOption) (*HumanScrollYResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HumanScrollYResponse)
	err := c.cc.Invoke(ctx, Browser_HumanScrollY_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) HumanScrollYTo(ctx context.Context, in *HumanScrollYToRequest, opts ...grpc.CallOption) (*HumanScrollYToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HumanScrollYToResponse)
	err := c.cc.Invoke(ctx, Browser_HumanScrollYTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) GetCookies(ctx context.Context, in *GetCookiesRequest, opts ...grpc.CallOption) (*GetCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCookiesResponse)
	err := c.cc.Invoke(ctx, Browser_GetCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) SetCookies(ctx context.Context, in *SetCookiesRequest, opts ...grpc.CallOption) (*SetCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCookiesResponse)
	err := c.cc.Invoke(ctx, Browser_SetCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, Browser_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*ReportResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResultResponse)
	err := c.cc.Invoke(ctx, Browser_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowserServer is the server API for Browser service.
// All implementations must embed UnimplementedBrowserServer
// for forward compatibility.
//
// Browser is what the SDK talks to. It is served by the control plane on
// loopback inside the worker, never on a routable interface.
//
// The SDK does not know where a browser actually runs and cannot be told. It
// asks for one; the control plane spawns a browser service in the worker
// environment, keeps the handle, and relays. That is what makes a session
// something the dashboard can list and watch — nothing is happening on a port
// only the tenant's code knows about.
//
// What neurun-browser serves on the other side is browserservice.proto. The two
// are deliberately separate: this one is a public contract with tenant code, and
// that one is an internal detail nothing outside the host may depend on.
type BrowserServer interface {
	// OpenSession spawns a browser and returns the session it created.
	OpenSession(context.Context, *OpenSessionRequest) (*Session, error)
	// Navigate drives the session to a URL.
	Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error)
	// WaitForNavigation blocks until the page the session is on has navigated.
	WaitForNavigation(context.Context, *WaitForNavigationRequest) (*WaitForNavigationResponse, error)
	// GetNode reads the first element a selector matches.
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// HumanMouseMove walks the pointer somewhere the way a hand would.
	HumanMouseMove(context.Context, *HumanMouseMoveRequest) (*HumanMouseMoveResponse, error)
	// HumanMouseClick walks the pointer somewhere and presses it.
	HumanMouseClick(context.Context, *HumanMouseClickRequest) (*HumanMouseClickResponse, error)
	// HumanType types, one key at a time, at a hand's pace.
	HumanType(context.Context, *HumanTypeRequest) (*HumanTypeResponse, error)
	// HumanScrollY turns the wheel down the page.
	HumanScrollY(context.Context, *HumanScrollYRequest) (*HumanScrollYResponse, error)
	// HumanScrollYTo turns the wheel until an element is where it was asked for.
	HumanScrollYTo(context.Context, *HumanScrollYToRequest) (*HumanScrollYToResponse, error)
	// GetCookies reads the session's whole jar.
	//
	// Browser-wide rather than per-origin, because that is what a profile keeps:
	// a partial read written back would delete the rest.
	GetCookies(context.Context, *GetCookiesRequest) (*GetCookiesResponse, error)
	// SetCookies puts a jar into the session, on top of what it holds.
	SetCookies(context.Context, *SetCookiesRequest) (*SetCookiesResponse, error)
	// CloseSession stops the browser and drops the session.
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	// ReportResult hands back what the app produced.
	//
	// The token says which execution this is, so an app cannot report for another
	// one. Reporting is what produces a result: an execution that exits without
	// reporting produced none, and fails saying so.
	ReportResult(context.Context, *ReportResultRequest) (*ReportResultResponse, error)
	mustEmbedUnimplementedBrowserServer()
}

// UnimplementedBrowserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserServer struct{}

func (UnimplementedBrowserServer) OpenSession(context.Context, *OpenSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedBrowserServer) Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Navigate not implemented")
}
func (UnimplementedBrowserServer) WaitForNavigation(context.Context, *WaitForNavigationRequest) (*WaitForNavigationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForNavigation not implemented")
}
func (UnimplementedBrowserServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedBrowserServer) HumanMouseMove(context.Context, *HumanMouseMoveRequest) (*HumanMouseMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HumanMouseMove not implemented")
}
func (UnimplementedBrowserServer) HumanMouseClick(context.Context, *HumanMouseClickRequest) (*HumanMouseClickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HumanMouseClick not implemented")
}
func (UnimplementedBrowserServer) HumanType(context.Context, *HumanTypeRequest) (*HumanTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HumanType not implemented")
}
func (UnimplementedBrowserServer) HumanScrollY(context.Context, *HumanScrollYRequest) (*HumanScrollYResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HumanScrollY not implemented")
}
func (UnimplementedBrowserServer) HumanScrollYTo(context.Context, *HumanScrollYToRequest) (*HumanScrollYToResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HumanScrollYTo not implemented")
}
func (UnimplementedBrowserServer) GetCookies(context.Context, *GetCookiesRequest) (*GetCookiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCookies not implemented")
}
func (UnimplementedBrowserServer) SetCookies(context.Context, *SetCookiesRequest) (*SetCookiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCookies not implemented")
}
func (UnimplementedBrowserServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedBrowserServer) ReportResult(context.Context, *ReportResultRequest) (*ReportResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedBrowserServer) mustEmbedUnimplementedBrowserServer() {}
func (UnimplementedBrowserServer) testEmbeddedByValue()                 {}

// UnsafeBrowserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserServer will
// result in compilation errors.
type UnsafeBrowserServer interface {
	mustEmbedUnimplementedBrowserServer()
}

func RegisterBrowserServer(s grpc.ServiceRegistrar, srv BrowserServer) {
	// If the following call pancis, it indicates UnimplementedBrowserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Browser_ServiceDesc, srv)
}

func _Browser_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_Navigate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).Navigate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_Navigate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).Navigate(ctx, req.(*NavigateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_WaitForNavigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForNavigationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).WaitForNavigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_WaitForNavigation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).WaitForNavigation(ctx, req.(*WaitForNavigationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_HumanMouseMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanMouseMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).HumanMouseMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_HumanMouseMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).HumanMouseMove(ctx, req.(*HumanMouseMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_HumanMouseClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanMouseClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).HumanMouseClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_HumanMouseClick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).HumanMouseClick(ctx, req.(*HumanMouseClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_HumanType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).HumanType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_HumanType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).HumanType(ctx, req.(*HumanTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_HumanScrollY_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanScrollYRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).HumanScrollY(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_HumanScrollY_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).HumanScrollY(ctx, req.(*HumanScrollYRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_HumanScrollYTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanScrollYToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).HumanScrollYTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_HumanScrollYTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).HumanScrollYTo(ctx, req.(*HumanScrollYToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_GetCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).GetCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_GetCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).GetCookies(ctx, req.(*GetCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_SetCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).SetCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_SetCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).SetCookies(ctx, req.(*SetCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Browser_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).ReportResult(ctx, req.(*ReportResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Browser_ServiceDesc is the grpc.ServiceDesc for Browser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Browser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neurun.browser.v1.Browser",
	HandlerType: (*BrowserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _Browser_OpenSession_Handler,
		},
		{
			MethodName: "Navigate",
			Handler:    _Browser_Navigate_Handler,
		},
		{
			MethodName: "WaitForNavigation",
			Handler:    _Browser_WaitForNavigation_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Browser_GetNode_Handler,
		},
		{
			MethodName: "HumanMouseMove",
			Handler:    _Browser_HumanMouseMove_Handler,
		},
		{
			MethodName: "HumanMouseClick",
			Handler:    _Browser_HumanMouseClick_Handler,
		},
		{
			MethodName: "HumanType",
			Handler:    _Browser_HumanType_Handler,
		},
		{
			MethodName: "HumanScrollY",
			Handler:    _Browser_HumanScrollY_Handler,
		},
		{
			MethodName: "HumanScrollYTo",
			Handler:    _Browser_HumanScrollYTo_Handler,
		},
		{
			MethodName: "GetCookies",
			Handler:    _Browser_GetCookies_Handler,
		},
		{
			MethodName: "SetCookies",
			Handler:    _Browser_SetCookies_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _Browser_CloseSession_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _Browser_ReportResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/browser.proto",
}
